dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - nightly

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist

script:
  - vendor/bin/tester -s -c tests/php.ini-unix tests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

stages:
  - Lint
  - Test
  - Code Quality

jobs:
  include:
    - stage: Test
      env: LOWEST_DEPENDENCIES
      php: 7.2
      install:
        - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-lowest

    - stage: Test
      env: DEV_DEPENDENCIES
      php: 7.4snapshot
      install:
        - composer config minimum-stability dev
        - travis_retry composer update --no-interaction --no-suggest --prefer-dist

    - stage: Test
      env: COVERAGE
      php: 7.2
      script:
        - vendor/bin/tester -s -p phpdbg -c ./tests/php.ini-unix --coverage ./coverage.xml --coverage-src ./src tests/
      after_script:
        - travis_retry wget -O /tmp/coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
        - php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true

    - stage: Lint
      before_script:
        - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
      script:
        - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt src/ tests/

    - stage: Code Quality
      env: STATIC_ANALYSIS
      script:
        - vendor/bin/phpstan analyse --ansi --no-progress -l max -c phpstan.neon src/ tests/

    - stage: Code Quality
      env: CODING_STANDARDS
      php: 7.2
      script:
        - vendor/bin/phpcs

  allow_failures:
    - php: nightly
    - env: DEV_DEPENDENCIES
